# Generated by Django 3.2.22 on 2024-02-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_postcode',
            new_name='default_eircode',
        ),
    ]
