# Generated by Django 3.2.22 on 2024-03-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='equiptment_featured',
            field=models.TextField(default='StuntScooter'),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default='SkatePark'),
        ),
    ]
