# Generated by Django 3.2.23 on 2024-02-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
