# Generated by Django 3.2.22 on 2024-02-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='customiseable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='custom',
        ),
    ]
